[package]
name = "bulletinboard"
version = "0.1.0"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]
description = "A general-purpose DHT"
homepage = "https://github.com/manuels/bulletinboard-dht"
license = " GPL-2.0"

[dependencies]
rand = "*"
rustc-serialize = "*"
time = "*"
log = "*"
env_logger = "*"
rust-crypto = "*"
docopt = "*"

[features]
default = ["dbus_service"]
"dbus_service" = ["dbus"]

[dependencies.dbus]
version = "*"
optional = true
