[package]
name = "bulletinboard"
version = "0.1.0"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]

[dependencies]
rand = "*"
rustc-serialize = "*"
time = "*"
log = "*"
env_logger = "*"
rust-crypto = "*"

[features]
default = ["dbus_service"]
"dbus_service" = ["dbus"]

[dependencies.dbus]
version = "*"
optional = true
